[versions]
antver = "1.10.15"
commonsbeanutilsver = "1.11.0"
commonscollections4ver = "4.5.0"
commonsconfiguration2ver = "2.12.0"
commonsdigester3ver = "3.2"
commonsexecver = "1.5.0"
commonsfileuploadver = "1.6.0"
commonsiover = "2.20.0"
commonslang3ver = "3.18.0"
commonsloggingver = "1.3.5"
commonstextver = "1.12.0"
commonsvalidatorver = "1.10.0"
gsonver = "2.13.1"
javaxwebsocketapiver = "1.1"
log4jver = "2.25.2"
mockitover = "1.10.19"
tomcatver = "9.0.108"

[libraries]
ant = { group = "org.apache.ant", name = "ant", version.ref ="antver" }

commonsbeanutils = { group = "commons-beanutils", name = "commons-beanutils", version.ref ="commonsbeanutilsver" }

commonscollections4 = { group = "org.apache.commons", name = "commons-collections4", version.ref ="commonscollections4ver" }

commonsconfiguration2 = { group = "org.apache.commons", name = "commons-configuration2", version.ref = "commonsconfiguration2ver" }

commonsdigester3 = { group = "org.apache.commons", name = "commons-digester3", version.ref ="commonsdigester3ver" }

commonsexec = { group = "org.apache.commons", name = "commons-exec", version.ref = "commonsexecver" }

commonsfileupload = { group = "commons-fileupload", name = "commons-fileupload", version.ref = "commonsfileuploadver" }

commonsio = { group = "commons-io", name = "commons-io", version.ref = "commonsiover" }

commonslang3 = { group = "org.apache.commons", name = "commons-lang3", version.ref = "commonslang3ver" }

commonslogging = { group = "commons-logging", name = "commons-logging", version.ref ="commonsloggingver" }

commonstext = { group = "org.apache.commons", name = "commons-text", version.ref ="commonstextver" }

commonsvalidator = { group = "commons-validator", name = "commons-validator", version.ref = "commonsvalidatorver" }

gson = { group = "com.google.code.gson", name = "gson", version.ref ="gsonver" }

javaxwebsocketapi = { group = "javax.websocket", name = "javax.websocket-api", version.ref ="javaxwebsocketapiver" }

log4j12api = { group = "org.apache.logging.log4j", name = "log4j-1.2-api", version.ref ="log4jver" }
log4japi = { group = "org.apache.logging.log4j", name = "log4j-api", version.ref ="log4jver" }
log4jappserver = { group = "org.apache.logging.log4j", name = "log4j-appserver", version.ref ="log4jver" }
log4jcore = { group = "org.apache.logging.log4j", name = "log4j-core", version.ref ="log4jver" }
log4jjcl = { group = "org.apache.logging.log4j", name = "log4j-jcl", version.ref ="log4jver" }
log4jslf4j2impl = { group = "org.apache.logging.log4j", name = "log4j-slf4j2-impl", version.ref ="log4jver" }

mockitoall = { group = "org.mockito", name = "mockito-all", version.ref ="mockitover" }

tomcatapi = { group = "org.apache.tomcat", name = "tomcat-api", version.ref ="tomcatver" }
tomcatcatalina = { group = "org.apache.tomcat", name = "tomcat-catalina", version.ref ="tomcatver" }
tomcatcoyote = { group = "org.apache.tomcat", name = "tomcat-coyote", version.ref ="tomcatver" }
tomcatelapi = { group = "org.apache.tomcat", name = "tomcat-el-api", version.ref ="tomcatver" }
tomcatjasper = { group = "org.apache.tomcat", name = "tomcat-jasper", version.ref ="tomcatver" }
tomcatjasperel = { group = "org.apache.tomcat", name = "tomcat-jasper-el", version.ref ="tomcatver" }
tomcatjspapi = { group = "org.apache.tomcat", name = "tomcat-jsp-api", version.ref ="tomcatver" }
tomcatjuli = { group = "org.apache.tomcat", name = "tomcat-juli", version.ref ="tomcatver" }
tomcatservletapi = { group = "org.apache.tomcat", name = "tomcat-servlet-api", version.ref ="tomcatver" }
tomcattribes = { group = "org.apache.tomcat", name = "tomcat-tribes", version.ref ="tomcatver" }
tomcatutil = { group = "org.apache.tomcat", name = "tomcat-util", version.ref ="tomcatver" }
tomcatutilscan = { group = "org.apache.tomcat", name = "tomcat-util-scan", version.ref ="tomcatver" }
tomcatwebsocket = { group = "org.apache.tomcat", name = "tomcat-websocket", version.ref ="tomcatver" }
tomcatwebsocketapi = { group = "org.apache.tomcat", name = "tomcat-websocket-api", version.ref ="tomcatver" }
